# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 7.1"
gem "puma", ">= 5.0"

# Observability
gem "opentelemetry-sdk"
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-instrumentation-all"
gem "prometheus-client"
gem "lograge"          # Structured JSON logging

# Minimal Rails API
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
